"""
Django settings for LittleLemonAPI project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-vw3h-7ndfr7*w7w9ktq(#no#$0f*45(el6$957$^%3#u(@83vk')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ['ALLOWED_HOSTS'].split(',') if os.environ.get('ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "rest_framework.authtoken",
    "djoser",
    "django_filters",
    "restaurant",
    "cart",
    "delivery_crew",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LittleLemonAPI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LittleLemonAPI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


if os.environ.get('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['POSTGRES_DB'],
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Cache
# Cache-aside layer for the public catalog (see restaurant/caching.py). Switches to
# Redis automatically when REDIS_HOST is set (docker-compose sets it); otherwise falls
# back to an in-process cache so local/test runs work with zero setup, same pattern as
# DATABASES above. IGNORE_EXCEPTIONS means a Redis outage degrades caching to "always
# miss" instead of a 500 - Redis is a performance layer here, never a source of truth.

if os.environ.get('REDIS_HOST'):
    redis_password = os.environ.get('REDIS_PASSWORD', '')
    redis_auth = f':{redis_password}@' if redis_password else ''
    redis_host = os.environ['REDIS_HOST']
    redis_port = os.environ.get('REDIS_PORT', '6379')
    redis_db = os.environ.get('REDIS_DB', '0')
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': f'redis://{redis_auth}{redis_host}:{redis_port}/{redis_db}',
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'IGNORE_EXCEPTIONS': True,
            },
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media (uploaded menu item images)
# Same pattern as DATABASES/CACHES above: local disk by default (docker-compose backs it
# with a named volume, same idea as postgres_data/redis_data), switching automatically to
# S3-compatible storage (MinIO or real S3) when MINIO_ENDPOINT is set. Application code
# (the model field, the serializer, the frontend) never knows or cares which is active -
# that's the whole point. See restaurant/models.py MenuItem.image and
# restaurant/serializers.py's RelativeImageField.

MEDIA_URL = '/media/'

if os.environ.get('MINIO_ENDPOINT'):
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
            'OPTIONS': {
                'endpoint_url': os.environ['MINIO_ENDPOINT'],
                'access_key': os.environ.get('MINIO_ACCESS_KEY', ''),
                'secret_key': os.environ.get('MINIO_SECRET_KEY', ''),
                'bucket_name': os.environ.get('MINIO_BUCKET', 'little-lemon-media'),
                'default_acl': None,
                'file_overwrite': False,
            },
        },
        'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
    }
else:
    MEDIA_ROOT = BASE_DIR / 'media'
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    # B24: restaurant.pagination.DefaultPagination adds a client-adjustable ?page_size=
    # (capped at 50) on top of DRF's plain PageNumberPagination.
    'DEFAULT_PAGINATION_CLASS': 'restaurant.pagination.DefaultPagination',
    # 2 made every list endpoint (menu, categories, orders, managers) nearly unusable - a
    # handful of items already spanned several pages. 12 is a sane default for a grid UI;
    # env-configurable like everything else in this file.
    'PAGE_SIZE': int(os.environ.get('PAGE_SIZE', 12)),
    "DEFAULT_THROTTLE_RATES": {
        "anon": "20/min",
        "user": "100/min",
    },
}

DJOSER = {
    "LOGIN_ID_FIELD": "username",
    "PASSWORD_RESET_CONFIRM_URL": "reset-password/{uid}/{token}",
    "USERNAME_RESET_CONFIRM_URL": "reset-username/{uid}/{token}",
    "EMAIL_FRONTEND_PROTOCOL": "http",
    "EMAIL_FRONTEND_DOMAIN": "localhost:3000",
    "EMAIL_FRONTEND_SITE_NAME": "Little Lemon",
    "SERIALIZERS": {
        # Adds a read-only "role" to GET/PATCH /api/users/me/ so the frontend can tell
        # managers, delivery crew and customers apart without guessing from a 403.
        "current_user": "restaurant.serializers.CurrentUserSerializer",
    },
}

# The frontend runs at EMAIL_FRONTEND_DOMAIN above and owns the /reset-password and /reset-username
# routes; it reads {uid}/{token} from the URL and calls the matching *_confirm endpoint.
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "noreply@littlelemon.local"
