# Generated by Django 5.2.11 on 2026-09-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_move_cart_to_cart_app"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeliveryCrewUser",
        ),
    ]
