# Generated by Django 5.2.11 on 2026-09-25 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0007_move_delivery_crew_to_delivery_crew_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="menuitem",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restaurant.menuitem",
            ),
        ),
    ]
