# Generated by Django 5.2.11 on 2026-09-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0008_orderitem_menuitem_set_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu-items/"),
        ),
    ]
